action:
  title: RJSF Example of Enumeration
  description: RJSF Enumeration arguments
  image: alpine:latest
  command: ["sh", "-c", "for i in $(seq 60); do echo $$i; sleep 1; done"]
  arguments:
    - name: select
      title: Select
      type: string
      enum: [ Ola, Hello, Bonjour, Buongiorno, GutenTag ]
    - name: radio
      title: Radio
      type: string
      enum: [ Ola, Hello, Bonjour, Buongiorno, GutenTag ]